config/routes.rb
Intentionist::Application.routes.draw do

  resources :providers

  resources :nodes

  root :to => "search#index"
  match '/search' => "search#create"

end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :input_type, :name, :output_type, :provider_id
  belongs_to :provider

  def input=(input)
    provider.inputs = input
  end

  def traversed?
    @traversed ||= false
  end

  def traverse
    @traversed = true
  end
end

app/models/provider.rb
class String
  def is_number?
    true if Float(self) rescue false
  end
end

class Provider < ActiveRecord::Base
  attr_accessible :apikey, :name, :url, :read_chain
  has_many :nodes

  def inputs=(input)
    @inputs = input
  end

  def inputs
    @inputs
  end

  def generate_url
    url = self.url
    url.scan(/%(\w+)%/).each do |type|
      if url.scan(/%(\w+)%/) then
        inputs.each do |input|
          if input[1].to_s.downcase == type[0].downcase then
            url.sub!("%#{input[1]}%", input[0])
          end
        end
      end
    end
      unless self.apikey.empty? then
        url += "&key=" + self.apikey
      else
        url
      end
  end

  def execute(output_type)
    clnt = HTTPClient.new
    result = JSON.parse(clnt.get_content(URI.encode(self.generate_url)))
    w = result
    self.read_chain.split(",").each do |s|
      if /\[(.*)\]/.match(s).nil? then
        if s.is_number? then
          w = w[s.to_i]
        else
          w = w[s.strip]
        end
      else
        ret = []
        s.split(";").each do |s|
          s.gsub!(/[\[\]]/, "")
          ret << w[s.strip]
        end
        return [ret.join(","), output_type]
      end
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/providers_controller.rb
require 'net/http'

require 'rubygems'
require 'json'

class ProvidersController < ApplicationController
  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @providers }
    end
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
    @provider = Provider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/new
  # GET /providers/new.json
  def new
    @provider = Provider.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/1/edit
  def edit
    @provider = Provider.find(params[:id])
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(params[:provider])

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render json: @provider, status: :created, location: @provider }
      else
        format.html { render action: "new" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /providers/1
  # PUT /providers/1.json
  def update
    @provider = Provider.find(params[:id])

    respond_to do |format|
      if @provider.update_attributes(params[:provider])
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy

    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end


  def create
    if params[:intent] == "eat" then 
      @output_type = "restaurant_name"
    end
    
    @node = Node.first
    begin
       @node = Node.find_by_output_type(@output_type)
       if @node.input_type == "address" then break
         else
           @node = Node.find_by_output_type(@node.input_type)
         end
    end while @node.input_type != "address"
    
    @result = [[params[:query], "query"], [params[:address], "address"]]
    
    while true
      @node.input = @result
      @result << @node.provider.execute(@node.output_type)
      if @node.output_type == @output_type then
        break
      end
      @node = Node.find_by_input_type(@node.output_type)
    end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intentionist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Intentionist</a>
    </div>
    </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :provider_id %><br />
    <%= f.text_field :provider_id %><br />
  </div>
  <div class="field">
    <%= f.label :input_type %><br />
    <%= f.text_field :input_type %>
  </div>
  <div class="field">
    <%= f.label :output_type %><br />
    <%= f.text_field :output_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Provider</th>
    <th>Input type</th>
    <th>Output type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.name %></td>
    <td><%= node.provider_id %></td>
    <td><%= node.input_type %></td>
    <td><%= node.output_type %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>

<p>
  <b>Provider:</b>
  <%= @node.provider_id %>
</p>

<p>
  <b>Input type:</b>
  <%= @node.input_type %>
</p>

<p>
  <b>Output type:</b>
  <%= @node.output_type %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :apikey %><br />
    <%= f.text_field :apikey %>
  </div>
  <div class="field">
    <%= f.label :read_chain %><br />
    <%= f.text_field :read_chain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Apikey</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @providers.each do |provider| %>
  <tr>
    <td><%= provider.name %></td>
    <td><%= provider.url %></td>
    <td><%= provider.apikey %></td>
    <td><%= link_to 'Show', provider %></td>
    <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
    <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @provider.name %>
</p>

<p>
  <b>Url:</b>
  <%= @provider.url %>
</p>

<p>
  <b>Apikey:</b>
  <%= @provider.apikey %>
</p>


<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>

app/views/search/create.html.erb
<%= @result.last[0] %>

app/views/search/index.html.erb
<div class="hero-unit">
  <h1>Intentionist Search</h1>
  <p>The new way to search intentionally</p>
</div>
<div class="span12">
  <%= form_tag("/search", :method => "get", :class => "inline") do %>
   <div class="input-append">
    <%= select_tag(:intent, options_for_select([['I want to know...', 'know'], ['I want to eat...', 'eat']])) %>
       <%= text_field_tag(:query, nil, :class => "input-xxlarge search-query") %>
       <%= submit_tag("Search", :class => "btn btn-primary") %>
    </div>
  <% end %>
</div>